[phases.setup]
nixPkgs = ["python311", "curl", "unzip", "glibc", "fontconfig", "nss", "atk", "at-spi2-core", "cups", "gtk3", "pango", "libdrm", "libxcomposite", "libxdamage", "libxrandr", "libxcb", "libxfixes", "libx11", "mesa", "libxext", "alsa-lib", "libxshmfence"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",

  # Download Chrome
  "curl -LO https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.92/linux64/chrome-linux64.zip",
  "unzip chrome-linux64.zip",
  "mv chrome-linux64 /opt/chrome",
  "chmod +x /opt/chrome/chrome",

  # Download ChromeDriver
  "curl -LO https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.92/linux64/chromedriver-linux64.zip",
  "unzip chromedriver-linux64.zip",
  "mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver",
  "chmod +x /usr/local/bin/chromedriver"
]

[phases.start]
cmd = "python3 Naukri.py"
